services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    networks:
      - poll-tier
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env  
    restart: always
 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: always
 
  worker:
    build: ./worker
    networks:
      - back-tier
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env  
    restart: always
 
  db:
    image: postgres:15-alpine
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql  
    env_file:
      - .env  
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
 
  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - result-tier    
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env  
    restart: always
 
volumes:
  db-data:
 
networks:
  back-tier:
  poll-tier:
  result-tier: